# **Machine Learning: Regularization**

- __Part 1: Vector Norms__

- __Part 2: Ridge Regression__

- __Part 3: Lasso Regression__

## Part 1: Vector Norms

- In general, a vector norm represents the size of a vector.

- **$l_2$ Norm**

    - Let $\mathbf{v}$ be an $n$-dimensional vector. Then, $$ \left \lVert \mathbf{v} \right \rVert_2 = \sqrt{v_1^2 + v_2^2 + \ldots + v_n^2}$$

    - Also known as Euclidean Distance

- **$l_1$ Norm**

    - Let $\mathbf{v}$ be an $n$-dimensional vector. Then, $$ \left \lVert \mathbf{v} \right \rVert_1 = |v_1| + |v_2| + \ldots + |v_n|$$

    - Also known as Manhattan Distance

- **$l_k$ Norm**

    - Let $\mathbf{v} \in \mathbb{R}^n$. Then, $$l_{k}(\mathbf{v}) = \left(\sum_{i=1}^{n} |v_i|^k\right)^{1/k}$$

### Example One

Let $\mathbf{v} \in \mathbb{R}^2$.
Consider,
$$ \left \lVert \mathbf{v} \right \rVert_2 = 3 \quad \text{and} \quad \left \lVert \mathbf{v} \right \rVert_1 = 3 $$
Geometrically represent each in $\mathbb{R}^2$.

## Part 2: Ridge Regression

- **Motivation**

    - Previously we explored $MSE$ and we understood the tradeoff between bias and variance when evaluating a model.

    - Our goal will be to find an $f$ that generalizes to out-of-sample data, or in a real application. To do this we will focus on reducing variance, but our tradeoff is an increase in bias.

- **Ridge Regression**

    - A regularized version of linear regression that imposes a regularization term, the $l_2$ norm of the weight vector $\Theta$, to the cost function.

    - Cost Function $$J(\Theta) = MSE(\Theta) + \lambda \cdot \sum_{i=1}^{n} (\Theta_i)^2 \quad \text{where,} \quad \lambda \in [0, \infty)$$

- **Naive Ridge Regression Example**

    - Generally, a good way to minimize overfitting is to _regularize_ the model. This can be thought of as imposing a set of constraints on our model so it does not over-learn the training data and perform poorly out-of-sample.

    - Let's explore Ridge Regression through the lens of linear regression.

    - First, let's consider $$\mathbf{y} = \mathbf{X} \cdot \hat{\boldsymbol{\beta}}$$

    - For this example, our model will have one feature. In reality, Ridge Regression and Lasso Regression are only used when we have two or more features. In our special case, we have: $$\hat{\boldsymbol{\beta}} = \begin{pmatrix} \beta_0 \\ \beta_1 \end{pmatrix}$$

    - Now, our goal has been to find $\hat{\boldsymbol{\beta}}$ such that: $$\min_{\hat{\boldsymbol{\beta}}} \left \lVert \mathbf{X} \cdot \hat{\boldsymbol{\beta}} - \mathbf{y} \right \rVert_2^2$$

    - For Ridge Regression we impose the constraint on $\hat{\boldsymbol{\beta}}$: $$\left \lVert \hat{\boldsymbol{\beta}} \right \rVert_2^2 \leq a^2 \quad \text{where} \quad a \in \mathbb{R}$$

    - To solve this, we can use Lagrange Multipliers. Rewriting in summation notation as, $$F(\beta_0, \beta_1, \lambda) = \sum_{i=1}^{n} (y_i - \beta_0 - \beta_1 \cdot x_i)^2 + \lambda \cdot ((\beta_0)^2 + (\beta_1)^2 - a^2)$$

    - Typically, we would proceed by taking partial derivatives of $F$ with respect to each variable. Creating a system of equations that we could then solve for each variable: $\beta_0$, $\beta_1$, and $\lambda$. Instead, we will simply treat $\lambda$ as a constant.

    - Thus, our new function becomes: $$\min_{\hat{\boldsymbol{\beta}}} \left \lVert \mathbf{X} \cdot \hat{\boldsymbol{\beta}} - \mathbf{y} \right \rVert_2^2 + \lambda \cdot \left \lVert \hat{\boldsymbol{\beta}} \right \rVert_2^2 \tag{1}$$

    - To minimize $(1)$ we can use a process such as Gradient Descent to solve for $\beta_0$ and $\beta_1$. We treat $\lambda$ as a constant, and in this case it will be a _hyperparameter_ that we can tune to our liking.

- **Practical Consideration**

    - It is important to scale the data as regularization is sensitive to the scale of the input features

    - Only used for models with two or more features

    - The Hyperparameter $\lambda$

        - If $\lambda = 0$ then the penalty vanishes and we recover a regular linear regression model

        - If $\lambda > 0$ then the penalty shrinks the coefficients toward zero, reducing variance at the cost of bias

        - Larger values of $\lambda$ will give a flat line through the mean

## Part 3: Lasso Regression

- **Lasso Regression**

    - A regularized version of linear regression that imposes a regularization term, the $l_1$ norm of the weight vector $\boldsymbol{\theta}$, to the cost function.

    - Cost Function $$J(\Theta) = MSE(\Theta) + \lambda \cdot \sum_{i=1}^{n} \left| \Theta_i \right| \quad \text{where,} \quad \lambda \in [0, \infty)$$

- **Practical Consideration**

    - Parameter Selection: Tends to reduce unimportant parameters (i.e. increases sparsity in $\Theta$), and thus can be used as a way to select features.

    - Allows a model to be built for a dataset that has more parameters than samples

In [25]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler

In [26]:
# Load in data

fh = "../data/growth_data.csv"

df = pd.read_csv(fh)

df.head()

,country_name,growth,oil,rgdp60,tradeshare,yearsschool,rev_coups,assasinations
0,India,1.915168,0,765.999817,0.140502,1.45,0.133333,0.866667
1,Argentina,0.617645,0,4462.001465,0.156623,4.99,0.933333,1.933333
2,Japan,4.304759,0,2953.999512,0.157703,6.71,0.000000,0.200000
3,Brazil,2.930097,0,1783.999878,0.160405,2.89,0.100000,0.100000
4,United States,1.712265,0,9895.003906,0.160815,8.66,0.000000,0.433333

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country_name   65 non-null     object
 1   growth         65 non-null     float64
 2   oil            65 non-null     int64
 3   rgdp60         65 non-null     float64
 4   tradeshare     65 non-null     float64
 5   yearsschool    65 non-null     float64
 6   rev_coups      65 non-null     float64
 7   assasinations  65 non-null     float64
dtypes: float64(6), int64(1), object(1)
memory usage: 4.2+ KB

In [28]:
# Quickly look for relationships

df[['growth', 'oil', 'rgdp60', 'tradeshare', 
    'yearsschool','rev_coups', 'assasinations']].corr()

,growth,oil,rgdp60,tradeshare,yearsschool,rev_coups,assasinations
growth,1.000000,NaN,0.062708,0.351682,0.330999,-0.285622,-0.150652
oil,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rgdp60,0.062708,NaN,1.000000,-0.153231,0.821148,-0.377262,-0.087869
tradeshare,0.351682,NaN,-0.153231,1.000000,-0.011311,-0.219323,-0.316384
yearsschool,0.330999,NaN,0.821148,-0.011311,1.000000,-0.334129,-0.125189
rev_coups,-0.285622,NaN,-0.377262,-0.219323,-0.334129,1.000000,0.490170
assasinations,-0.150652,NaN,-0.087869,-0.316384,-0.125189,0.490170,1.000000

In [29]:
# Select and standardize features, and add ones

X = df[['tradeshare', 'yearsschool']].values

scaler = StandardScaler()

X = scaler.fit_transform(X)

X_b = np.c_[np.ones((len(X), 1)), X]
X_b[:5]

array([[ 1.        , -1.47786432, -1.00503738],
       [ 1.        , -1.42170073,  0.39840411],
       [ 1.        , -1.41793729,  1.0803024 ],
       [ 1.        , -1.40852433, -0.43414586],
       [ 1.        , -1.40709608,  1.85338456]])

In [30]:
# Select target

y = df['growth']
y.head()

0    1.915168
1    0.617645
2    4.304759
3    2.930097
4    1.712265
Name: growth, dtype: float64

In [31]:
# Non-linear function

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [32]:
# Data for MSE Surface
b0_fixed = float(np.mean(np.sin(y.values.reshape(-1, 1))))
b1_vals = np.linspace(-5, 5, 200)
b2_vals = np.linspace(-5, 5, 200)
B1, B2 = np.meshgrid(b1_vals, b2_vals)

y_nl = np.sin(y.values.reshape(-1, 1))

alpha = 0.10

Z = np.array([
    np.mean((y_nl - np.sin(X @ np.array([[b1], [b2]]) + b0_fixed)) ** 2 ) + alpha * (np.abs(b1) + np.abs(b2))
    for b1, b2 in zip(B1.ravel(), B2.ravel())
]).reshape(B1.shape)


# Stochstic Gradient Descent
n_epochs = 50
t0, t1 = 20, 100
n = len(X)
def learning_schedule(t):
    return t0 / (t + t1)

trace = []
beta = np.array([[4], [-4]])
for epoch in range(n_epochs):
    for i in range(n):
        mse = np.mean((y_nl - np.sin(X @ beta + b0_fixed)) ** 2) + alpha * (np.abs(beta[0]) + np.abs(beta[1]))
        trace.append((i, beta[0], beta[1], mse))

        rand_idx = np.random.randint(n)
        xi = X[rand_idx:rand_idx+1]
        yi = y_nl[rand_idx:rand_idx+1]
        gradients = 2 * xi.T.dot(np.sin(xi @ beta + b0_fixed) - yi) + alpha * np.sign(beta)
        eta = learning_schedule(epoch * n + i)
        beta = beta - eta * gradients

# Constraint constant a set at the minimum MSE
b1_final, b2_final = float(beta[0].item()), float(beta[1].item())
a = abs(b1_final) + abs(b2_final)
z_min = float(Z.min())
diamond_x = [a, 0, -a, 0, a]
diamond_y = [0, a, 0, -a, 0]
diamond_z = [z_min, z_min, z_min, z_min, z_min]

# Plotting
fig = go.Figure(
    data=[
        go.Surface(
            x=B1,
            y=B2,
            z=Z,
            colorscale='Oranges',
            opacity=0.8,
            showscale=False
        ),
        go.Scatter3d(
            x=[float(trace[0][1].item())],
            y=[float(trace[0][2].item())],
            z=[float(trace[0][3].item())],
            mode='markers',
            marker=dict(color='blue', size=10)
        ),
        go.Scatter3d(
            x=diamond_x,
            y=diamond_y,
            z=diamond_z,
            mode='lines',
            line=dict(color='green', width=5)
        )
    ]
)

fig.update_layout(
    scene=dict(
        xaxis_title='b1 (tradeshare)',
        yaxis_title='b2 (yearsschool)',
        zaxis_title='MSE Cost',
    ),
    title=dict(text="<b>Cost Function Surface of a Non-linear Model</b>", font=dict(size=26)),
    height=900, 
    width=900,
    updatemenus=[dict(
        type="buttons",
        bgcolor="white",
        font=dict(color="black", size=14),
        buttons=[dict(
            args=[None, {
                "frame": {"duration": 80, "redraw": True},
                "fromcurrent": True,
                "transition": {"duration": 0}
            }],
            label="Play",
            method="animate"
        )]
    )],
    font=dict(size=14),
    template="plotly_dark",
    showlegend=False
)

fig.update(frames=[go.Frame(
    data=[go.Scatter3d(
        x=[float(trace[i][1].item())],
        y=[float(trace[i][2].item())],
        z=[float(trace[i][3].item())],
        name='gradient')],
    traces=[1],
    name=str(i)
    )
    for i in range(0, len(trace), 2)])

fig.show()

### References

1. **Géron, A.** Hands-on Machine Learning with Scikit-Learn, Keras & TensorFlow: Concepts, Tools, and Techniques to Build Intelligent Systems (2nd ed.). O'Reilly Media.